path_base = "D:/WorkingPlaces/outputs/parking_planning/"

path_dataset = path_base + "datasets/"
path_dataset_pkl = path_dataset + "dataset_all.pkl"
path_solutions = path_dataset + "solutions/"
path_anchors = path_dataset + "anchors_list.txt"
path_anchors_failed = path_dataset + "anchors_failed_list.txt"
path_figs = path_base + "figs/"
path_figs_all = path_figs + "all/"
path_figs_init = path_figs + "init/"
path_figs_train = path_figs + "train/"
path_figs_test = path_figs + "test/"
path_figs_once = path_figs + "once/"
path_figs_failed = path_figs + "failed/"
path_log = path_base + "log.txt"
path_result = path_base + "result.txt"
path_pts = path_dataset + "pts/"
path_pt_best = path_pts + "00_best.pt"
